[package]
name = "shodan-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
url = "2.3"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }